"""Inventory the original MATLAB code: every .m file, the toolbox functions it calls, data files it reads.

Usage:
    python tools/inventory_matlab.py                 # all chapters -> analysis/_matlab_inventory.md + .json
    python tools/inventory_matlab.py --chapter ch2   # one folder

The output is the starting point for analysis/chNN.md. It is deliberately conservative (regex-based);
the chapter-analyst agent must still read every file.
"""
from __future__ import annotations

import argparse
import json
import re
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]  # C:/Users/sislam27/Work/Climate Dynamics PHD/Sea Ice Image Processing with MATLAB


def locate_matlab_root() -> Path:
    """book.yaml → book.matlab_root (default 'K30735_..._matlab codes/matlab'); else search for a 'matlab' dir containing ch2."""
    import yaml
    cfg = yaml.safe_load((ROOT / "book.yaml").read_text(encoding="utf-8"))
    cand = ROOT / cfg["book"].get("matlab_root", "K30735_Sea Ice Image Processing with MATLAB_matlab codes/matlab")
    if (cand / "ch2").exists():
        return cand
    for p in ROOT.rglob("ch2"):
        if p.is_dir() and p.parent.name.lower() == "matlab" and ".venv" not in p.parts:
            print(f"NOTE: book.yaml matlab_root not found; using detected {p.parent}")
            return p.parent
    raise SystemExit(f"Cannot find the MATLAB code folder (expected {cand}). Fix book.yaml → book.matlab_root.")


MATLAB_ROOT = locate_matlab_root()

# Functions worth flagging because their Python equivalents are non-trivial (see function_map.md)
WATCHLIST = {
    "imread", "rgb2gray", "im2bw", "graythresh", "imbinarize", "adaptthresh", "kmeans", "imhist", "histeq", "imadjust",
    "bwlabel", "bwconncomp", "regionprops", "bwdist", "bwmorph", "bwperim", "bwboundaries", "bwareaopen", "bwtraceboundary",
    "imfill", "imreconstruct", "imregionalmax", "imregionalmin", "imextendedmax", "imextendedmin", "imhmax", "imhmin",
    "imimposemin", "watershed", "strel", "imerode", "imdilate", "imopen", "imclose", "imtophat", "imbothat",
    "imfilter", "conv2", "fspecial", "edge", "medfilt2", "ordfilt2", "stdfilt", "entropyfilt", "imgradient",
    "imresize", "interp2", "rgb2hsv", "hsv2rgb", "rgb2ind", "ind2rgb", "mat2gray", "im2double", "im2uint8",
    "imcomplement", "gradient", "del2", "hough", "houghpeaks", "houghlines", "poly2mask", "roipoly", "imcrop",
    "graycomatrix", "graycoprops", "activecontour", "VideoReader", "read", "padarray", "sub2ind", "ind2sub",
    "find", "round", "fix", "mod", "rem", "cellfun", "arrayfun", "polyfit", "polyval", "fminsearch", "lsqnonlin",
    "imshow", "imwrite", "figure", "subplot", "plot", "contour", "quiver", "label2rgb", "montage",
}

CALL_RE = re.compile(r"\b([A-Za-z_]\w*)\s*\(")
FILE_RE = re.compile(r"['\"]([^'\"]+\.(?:jpg|jpeg|png|bmp|tif|tiff|mat|avi|mp4|txt|csv))['\"]", re.I)
DEF_RE = re.compile(r"^\s*function\s+(?:\[?[\w,\s]*\]?\s*=\s*)?([A-Za-z_]\w*)", re.M)


def analyze_file(path: Path) -> dict:
    src = path.read_text(encoding="utf-8", errors="replace")
    code_lines = [l for l in src.splitlines() if not l.strip().startswith("%")]
    code = "\n".join(code_lines)
    calls = Counter(CALL_RE.findall(code))
    defs = DEF_RE.findall(src)
    return {
        "file": str(path.relative_to(ROOT)).replace("\\", "/"),
        "lines": len(src.splitlines()),
        "defines": defs,
        "is_function_file": bool(defs),
        "calls_watchlist": sorted(c for c in calls if c in WATCHLIST),
        "calls_all": sorted(calls),
        "data_files": sorted(set(FILE_RE.findall(src))),
        "comment_head": "\n".join(l for l in src.splitlines()[:12] if l.strip().startswith("%")),
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--chapter", default=None, help="e.g. ch2 (folder name under MATLAB_ROOT, see book.yaml)")
    args = ap.parse_args()

    folders = [MATLAB_ROOT / args.chapter] if args.chapter else sorted(
        p for p in MATLAB_ROOT.iterdir() if p.is_dir())
    out_dir = ROOT / "analysis"
    out_dir.mkdir(exist_ok=True)
    inventory: dict[str, list[dict]] = {}
    md = ["# MATLAB inventory (auto-generated by tools/inventory_matlab.py)\n"]
    for folder in folders:
        m_files = sorted(folder.rglob("*.m"))
        other = sorted(p for p in folder.rglob("*") if p.is_file() and p.suffix.lower() != ".m")
        inventory[folder.name] = [analyze_file(p) for p in m_files]
        md.append(f"\n## {folder.name}  ({len(m_files)} .m files, {len(other)} data/other files)\n")
        md.append("Data/other files: " + ", ".join(str(p.relative_to(folder)).replace("\\", "/") for p in other) + "\n")
        for info in inventory[folder.name]:
            kind = "function" if info["is_function_file"] else "script"
            md.append(f"- `{info['file']}` — {kind}, {info['lines']} lines; defines {info['defines'] or '-'}; "
                      f"watchlist calls: {', '.join(info['calls_watchlist']) or '-'}; reads: {info['data_files'] or '-'}")
    (out_dir / "_matlab_inventory.json").write_text(json.dumps(inventory, indent=2), encoding="utf-8")
    (out_dir / "_matlab_inventory.md").write_text("\n".join(md), encoding="utf-8")
    print("\n".join(md))
    print(f"\nWrote {out_dir / '_matlab_inventory.md'} and .json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
